### ISSUE TITLE
Lab 1: Don't copy the template to the main document

### ISSUE THREAD

**Issue by bobvdb** [JohnGorter/Polymer_training#1]
In lab 1 the template gets copied to the owner document and afterwards retrieved with 
`document.querySelector("#mytemplate").content`.

If you use the owner document here instead of the root document, you don't need to copy over the template.
`document.currentScript.ownerDocument.querySelector("#mytemplate").content`

Advantage: template is still private so no conflicts in names

**Comment by JohnGorter** [comment]
Verwerkt in de huidige versie!
